on:
  push:
    paths:
      - 'jav_study/**'

name: Release

permissions: write-all



jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Release-PR
        uses:  google-github-actions/release-please-action@v3.1.2
        with:
          release-type: node
          token: ${{secrets.JAV_RELEASE}}
          pull-request-title-pattern: "chore${scope}: release ${version}"
          extra-files: jav_study/manifest.json


